export const colleges = [
    // IITs
    'IIT Bombay',
    'IIT Delhi',
    'IIT Madras',
    'IIT Kanpur',
    'IIT Kharagpur',
    'IIT Roorkee',
    'IIT Guwahati',
    'IIT Hyderabad',
    'IIT Indore',
    'IIT Varanasi (BHU)',
    'IIT Gandhinagar',
    'IIT Ropar',
    'IIT Bhubaneswar',
    'IIT Jodhpur',
    'IIT Patna',
    'IIT Mandi',
    'IIT Tirupati',
    'IIT Palakkad',
    'IIT Goa',
    'IIT Bhilai',
    'IIT Dharwad',
    'IIT Jammu',
    'ISM Dhanbad',

    // NITs
    'NIT Agartala',
    'NIT Allahabad (MNNIT)',
    'NIT Andhra Pradesh',
    'NIT Arunachal Pradesh',
    'NIT Bhopal (MANIT)',
    'NIT Calicut',
    'NIT Delhi',
    'NIT Durgapur',
    'NIT Goa',
    'NIT Hamirpur',
    'NIT Jaipur (MNIT)',
    'NIT Jalandhar',
    'NIT Jamshedpur',
    'NIT Kurukshetra',
    'NIT Manipur',
    'NIT Meghalaya',
    'NIT Mizoram',
    'NIT Nagaland',
    'NIT Nagpur (VNIT)',
    'NIT Patna',
    'NIT Puducherry',
    'NIT Raipur',
    'NIT Rourkela',
    'NIT Sikkim',
    'NIT Silchar',
    'NIT Srinagar',
    'NIT Surathkal',
    'NIT Trichy',
    'NIT Uttarakhand',
    'NIT Warangal',

    // IIITs
    'IIIT Allahabad',
    'IIIT Bangalore',
    'IIIT Delhi',
    'IIIT Hyderabad',
    'IIITDM Jabalpur',
    'IIITDM Kancheepuram',
    'ABV-IIITM Gwalior',
    'IIIT Pune',
    'IIIT Lucknow',
    'IIIT Sonepat',
    'IIIT Kota',
    'IIIT Guwahati',
    'IIIT Vadodara',
    'IIIT Sri City',
    'IIIT Nagpur',
    'IIIT Una',
    'IIIT Dharwad',
    'IIIT Bhagalpur',
    'IIIT Bhopal',
    'IIIT Surat',
    'IIIT Ranchi',

    // Central & Top Universities
    'University of Delhi (DU)',
    'Jawaharlal Nehru University (JNU)',
    'Banaras Hindu University (BHU)',
    'Aligarh Muslim University (AMU)',
    'Jamia Millia Islamia',
    'University of Hyderabad',
    'University of Mumbai',
    'University of Calcutta',
    'Jadavpur University',
    'Anna University',
    'Osmania University',
    'Savitribai Phule Pune University',
    'Tezpur University',
    'Visva-Bharati University',
    'Pondicherry University',
    'North Eastern Hill University',

    // Top Private/Others
    'BITS Pilani',
    'BITS Goa',
    'BITS Hyderabad',
    'VIT Vellore',
    'VIT Chennai',
    'SRM Institute of Science and Technology',
    'Manipal Academy of Higher Education',
    'Amity University',
    'Thapar Institute of Engineering and Technology',
    'Symbiosis International University',
    'Christ University',
    'Chandigarh University',
    'Lovely Professional University',
    'Kalinga Institute of Industrial Technology (KIIT)',
    'Shiv Nadar University',
    'Ashoka University'
].sort();

export const CATEGORIES = [
    { name: 'Categories', value: '' },
    { name: 'Clothes', value: 'clothes' },
    { name: 'Mobiles & Laptops', value: 'mobiles_laptops' },
    { name: 'Electronics', value: 'electronics' },
    { name: 'Furniture', value: 'furniture' },
    { name: 'Books', value: 'books' },
    { name: 'Sports', value: 'sports' },
    { name: 'Vehicles', value: 'vehicles' },
    { name: 'Accessories', value: 'accessories' },
    { name: 'Stationery', value: 'stationery' },
    { name: 'Musical Instruments', value: 'instruments' }
];
