export const colleges = [
    // IITs
    'IIT Bombay',
    'IIT Delhi',
    'IIT Madras',
    'IIT Kanpur',
    'IIT Kharagpur',
    'IIT Roorkee',
    'IIT Guwahati',
    'IIT Hyderabad',
    'IIT Indore',
    'IIT Varanasi (BHU)',
    'IIT Gandhinagar',
    'IIT Ropar',
    'IIT Bhubaneswar',
    'IIT Jodhpur',
    'IIT Patna',
    'IIT Mandi',
    'IIT Tirupati',
    'IIT Palakkad',
    'IIT Goa',
    'IIT Bhilai',
    'IIT Dharwad',
    'IIT Jammu',
    'ISM Dhanbad',

    // NITs
    'NIT Agartala',
    'NIT Allahabad (MNNIT)',
    'NIT Andhra Pradesh',
    'NIT Arunachal Pradesh',
    'NIT Bhopal (MANIT)',
    'NIT Calicut',
    'NIT Delhi',
    'NIT Durgapur',
    'NIT Goa',
    'NIT Hamirpur',
    'NIT Jaipur (MNIT)',
    'NIT Jalandhar',
    'NIT Jamshedpur',
    'NIT Kurukshetra',
    'NIT Manipur',
    'NIT Meghalaya',
    'NIT Mizoram',
    'NIT Nagaland',
    'NIT Nagpur (VNIT)',
    'NIT Patna',
    'NIT Puducherry',
    'NIT Raipur',
    'NIT Rourkela',
    'NIT Sikkim',
    'NIT Silchar',
    'NIT Srinagar',
    'NIT Surathkal',
    'NIT Trichy',
    'NIT Uttarakhand',
    'NIT Warangal',

    // IIITs
    'IIIT Allahabad',
    'IIIT Bangalore',
    'IIIT Delhi',
    'IIIT Hyderabad',
    'IIITDM Jabalpur',
    'IIITDM Kancheepuram',
    'ABV-IIITM Gwalior',
    'IIIT Pune',
    'IIIT Lucknow',
    'IIIT Sonepat',
    'IIIT Kota',
    'IIIT Guwahati',
    'IIIT Vadodara',
    'IIIT Sri City',
    'IIIT Nagpur',
    'IIIT Una',
    'IIIT Dharwad',
    'IIIT Bhagalpur',
    'IIIT Bhopal',
    'IIIT Surat',
    'IIIT Ranchi',

    // Central & Top Universities
    'University of Delhi (DU)',
    'Jawaharlal Nehru University (JNU)',
    'Banaras Hindu University (BHU)',
    'Aligarh Muslim University (AMU)',
    'Jamia Millia Islamia',
    'University of Hyderabad',
    'University of Mumbai',
    'University of Calcutta',
    'Jadavpur University',
    'Anna University',
    'Osmania University',
    'Savitribai Phule Pune University',
    'Tezpur University',
    'Visva-Bharati University',
    'Pondicherry University',
    'North Eastern Hill University',
    'Hyderabad Central University',
    'University of Kerala',
    'Mahatma Gandhi University',
    'Calicut University',
    'Andhra University',
    'Sri Venkateswara University',
    'Cochin University of Science and Technology (CUSAT)',

    // Delhi NCR State / Deemed Universities
    'Delhi Technological University (DTU)',
    'Netaji Subhas University of Technology (NSUT)',
    'Guru Gobind Singh Indraprastha University (GGSIPU)',
    'Jamia Hamdard',
    'Gautam Buddha University',
    'Galgotias University',
    'Noida International University',
    'Sharda University',
    'Bennett University',
    'G.L. Bajaj Institute of Technology and Management',

    // Maharashtra Engineering & Universities
    'MIT World Peace University (MIT WPU)',
    'MIT ADT University',
    'College of Engineering Pune (COEP)',
    'Pune Institute of Computer Technology (PICT)',
    'Vishwakarma Institute of Technology (VIT Pune)',
    'Maharashtra Institute of Technology (MIT Pune)',
    'Symbiosis Institute of Technology (SIT)',
    'Cummins College of Engineering',
    "MAEER's MIT College of Engineering",
    'Dr. D.Y. Patil Institute of Technology',
    'Pimpri Chinchwad College of Engineering (PCCOE)',
    'Sinhgad College of Engineering',
    'Rajarshi Shahu College of Engineering (RSCOE)',
    'Bharati Vidyapeeth College of Engineering',
    'G.H. Raisoni College of Engineering',
    'Shri Ramdeobaba College of Engineering (RCOEM)',
    'YCCE Nagpur',
    "KIT's College of Engineering",
    'Walchand College of Engineering',
    'VJTI Mumbai',
    'ICT Mumbai',
    'SPIT Mumbai',
    'K.J. Somaiya College of Engineering',
    'DJ Sanghvi College of Engineering',
    'Fr. Conceicao Rodrigues College of Engineering (CRCE)',
    'Don Bosco Institute of Technology (DBIT)',
    'Thadomal Shahani Engineering College (TSEC)',

    // Karnataka Engineering & Universities
    'PES University',
    'RV College of Engineering',
    'MS Ramaiah Institute of Technology (MSRIT)',
    'Ramaiah University of Applied Sciences',
    'BMS College of Engineering',
    'Dayananda Sagar University',
    'JSS Science and Technology University',
    'KLE Technological University',
    'New Horizon College of Engineering',
    'Alliance University',
    'CMR University',
    'Reva University',
    'Presidency University',
    'NMAM Institute of Technology',
    'Nitte Meenakshi Institute of Technology',
    'BGS College of Engineering',
    'Sahyadri College of Engineering',

    // Andhra Pradesh & Telangana
    'GITAM University',
    'KL University (Koneru Lakshmaiah)',
    'Vignan University',
    'SRM University AP',
    'VIT AP',
    'JNTU Hyderabad',
    'JNTU Kakinada',
    'JNTU Anantapur',
    'Vellore Institute of Technology (VIT Amaravati)',
    'Sreenidhi Institute of Science and Technology',
    'CVR College of Engineering',

    // Tamil Nadu
    'PSG College of Technology',
    'College of Engineering Guindy (CEG)',
    'Thiagarajar College of Engineering',
    'Coimbatore Institute of Technology',
    'Sri Sivasubramaniya Nadar College of Engineering',
    'Kongu Engineering College',
    'Kumaraguru College of Technology',
    'Saveetha University',
    'Sathyabama Institute of Science and Technology',

    // Kerala
    'TKM College of Engineering',
    'Government Engineering College Thrissur',
    'Rajagiri School of Engineering & Technology',
    'Mar Baselios College of Engineering',
    'Model Engineering College',

    // Rajasthan & MP
    'Rajasthan Technical University',
    'JECRC University',
    'Poornima University',
    'Maulana Azad National Institute of Technology (MANIT)',
    'SGSITS Indore',
    'IPS Academy',

    // UP & Uttarakhand
    'Dr. APJ Abdul Kalam Technical University (AKTU)',
    'Graphic Era University',
    'DIT University',
    'Hindustan College of Science & Technology',
    'HBTU Kanpur',
    'Bundelkhand University',

    // Punjab, Haryana & Himachal
    'Panjab University',
    'Punjab Engineering College (PEC)',
    'Guru Nanak Dev University',
    'Chitkara University',
    'GNA University',
    'Maharishi Markandeshwar University',
    'Kurukshetra University',
    'YMCA University of Science & Technology',

    // Gujarat
    'Gujarat Technological University (GTU)',
    'Dhirubhai Ambani Institute (DAIICT)',
    'Nirma University',
    'Pandit Deendayal Energy University (PDEU)',
    'LD College of Engineering',
    'Silver Oak University',
    'Marwadi University',

    // West Bengal & Odisha
    'Heritage Institute of Technology',
    'Techno India University',
    'IIEST Shibpur',
    'Silicon Institute of Technology',
    'C.V. Raman Global University',
    'ITER Bhubaneswar',

    // Top Private/Deemed
    'BITS Pilani',
    'BITS Goa',
    'BITS Hyderabad',
    'VIT Vellore',
    'VIT Chennai',
    'VIT Bhopal',
    'SRM Institute of Science and Technology',
    'SRM University Sonepat',
    'Manipal Academy of Higher Education',
    'Amity University',
    'Thapar Institute of Engineering and Technology',
    'Symbiosis International University',
    'Christ University',
    'Chandigarh University',
    'Lovely Professional University',
    'Kalinga Institute of Industrial Technology (KIIT)',
    'Shiv Nadar University',
    'Ashoka University',
    'O.P. Jindal Global University',
    'FLAME University',
    'Azim Premji University',
    'Plaksha University',
    'BML Munjal University',
    'GD Goenka University',
    'Birla Institute of Technology Mesra (BIT Mesra)',
    'NMIMS Mumbai',
    'ICFAI University',
    'Jain University',
    'Hindustan Institute of Technology and Science',
    'Vel Tech University',
    'Karunya Institute of Technology',
    'Bannari Amman Institute of Technology',
].sort();

export const CATEGORIES = [
    { name: 'Categories', value: '' },
    { name: 'Clothes', value: 'clothes' },
    { name: 'Mobiles & Laptops', value: 'mobiles_laptops' },
    { name: 'Electronics', value: 'electronics' },
    { name: 'Furniture', value: 'furniture' },
    { name: 'Books', value: 'books' },
    { name: 'Sports', value: 'sports' },
    { name: 'Vehicles', value: 'vehicles' },
    { name: 'Accessories', value: 'accessories' },
    { name: 'Stationery', value: 'stationery' },
    { name: 'Musical Instruments', value: 'instruments' }
];
